### ISSUE TITLE
file: part1/motivation

### ISSUE THREAD

**Issue by acocac** [pangeo-data/pangeo-openeo-BiDS-2023#17]

**Comment by acocac** [comment]
Maybe we can reuse markdown from what we have at https://github.com/galaxyproject/training-material/blob/main/topics/climate/tutorials/pangeo-notebook/slides.html (and split motivation & overview)

_Originally posted by @annefou in https://github.com/pangeo-data/pangeo-openeo-BiDS-2023/pull/14#discussion_r1370055246_

**Comment by tinaok** [comment]
re-organisation of introduction and motivation ,

**Comment by acocac** [comment]
fixed in #89
