### ISSUE TITLE
file: before/setup

### ISSUE THREAD

**Issue by tinaok** [pangeo-data/pangeo-openeo-BiDS-2023#26]
- [x] take out Enroll to the [vo.notebooks.egi.eu](http://vo.notebooks.egi.eu/) ? 
- [x] update the infrastructure from foss4g to pangeo-eosc (https://github.com/pangeo-data/pangeo-eosc/blob/main/users/users-getting-started.md)

**Comment by tinaok** [comment]
@annefou can you please confirm for the part of vo.notebooks?

**Comment by annefou** [comment]
It looks good to me. I am just a bit unsure for the minIO part.  We can ask for instance Amin Razbani to test it as he has not signed up yet.
