### ISSUE TITLE
part2 title and page connection does not match

### ISSUE THREAD

**Issue by tinaok** [pangeo-data/pangeo-openeo-BiDS-2023#63]
@acocac  any idia how to fix it?  

<img width="1313" alt="スクリーンショット 2023-11-03 19 33 55" src="https://github.com/pangeo-data/pangeo-openeo-BiDS-2023/assets/46813815/8df89c2e-1e2c-4867-abe0-1aa32934ec37">

**Comment by acocac** [comment]
This will be fixed if you open the website in an incognito mode, or delete
the cache of your browser.

**Comment by acocac** [comment]
Fixed.
