### ISSUE TITLE
OpenEO connection fails in automatic build.

### ISSUE THREAD

**Issue by tinaok** [pangeo-data/pangeo-openeo-BiDS-2023#64]
https://pangeo-data.github.io/pangeo-openeo-BiDS-2023/part2/openEO%20-%20Client%20Side%20Land%20Cover%20Alps.html
OpenEO connection would not work as no one click it from jupyterbook build! 
Probably we need to deactivate automatic run?  How can we do it? @acocac

**Comment by acocac** [comment]
We can exclude the notebook using `exclude_patterns` arg in [_config.yml](https://jupyterbook.org/en/stable/customize/config.html)

**Comment by acocac** [comment]
Is this still an issue @tinaok?

**Comment by acocac** [comment]
Fixed in #69. Thanks @annefou
